spring:
  forth-datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.20.65:1521:OBZMETA
    username: ECUBE
    password: digital1!
  second-datasource:
    url: jdbc:oracle:thin:@192.168.20.65:1521:OBZMETA
    driver-class-name: oracle.jdbc.OracleDriver
    password: digital1!
    username: ECUBEEBM
  third-datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ECUBE
    password: digital1!
    url: jdbc:oracle:thin:@192.168.20.65:1521:OBZMETA
  datasource:
    password: digital1!
    driver-class-name: oracle.jdbc.OracleDriver
    username: DSDMT
    url: jdbc:oracle:thin:@192.168.20.65:1521:OBZMETA
  redis_cluster:
    cluster:
      nodes: 192.168.20.51:6000,192.168.20.52:6000,192.168.20.53:6000
  redis_single:
    host: 192.168.20.57
    port: 6379
server:
  max-http-header-size: '1000000'
  port: '8095'
